### PR TITLE
Fix RBNF Tokenizer rule recogniser and add a NotImplementedException error subclass

### PR DESCRIPTION
**Pull request by radzinzki**
### Problem
While working on #62, I realised that some RBNF rules didn't work. (`Exception: Cannot call method 'rule_for' of null`).

### Cause
The RBNF tokenizer didn't tokenise some rules correctly. The Rule recognizer regex wasn't being generated properly because I was calling the wrong method(s) (oops!). This led to a few exceptions when querying a subset of the rules. This exception was being suppressed because the test was ignoring _all_ exceptions in the RNBF tests rather than only the tests for rules which weren't implemented. I've added a `NotImplementedException` error subclass and tests only skip on these errors now.

(Should I go ahead and throw this exception everywhere in the library where stuff isn't implemented? For instance [here](https://github.com/twitter/twitter-cldr-js/blob/b92a255c77d8864fecd377895ea137f0fb41afb0/lib/twitter_cldr/js/mustache/implementation/calendars/datetime.coffee#L100) or [here](https://github.com/twitter/twitter-cldr-js/blob/b92a255c77d8864fecd377895ea137f0fb41afb0/lib/twitter_cldr/js/mustache/implementation/calendars/datetime.coffee#L103))

#### Notes:
- This branched is based off of the branch for #62 and should be merged after that one is merged. Till then the change-set won't be of much help. 😅
- A downside of this is that now the tests take a really long time (there are about 30k tests). I've made [this PR](https://github.com/radzinzki/twitter-cldr-js/pull/1) to address this.

@KL-7 @camertron

### CODE REVIEW

**Comment by camertron** [comment]
It's going to be a lot easier to review this after #62 is merged :smile:

**Comment by radzinzki** [comment]
Indeed 😅

**Comment by camertron** [comment]
Hey @radzinzki can you update this branch now that #62 has been merged?

**Comment by radzinzki** [comment]
@camertron, done! This should make way more sense now. 😅

Also, now that #62 is merged, I'll open [my other PR](https://github.com/radzinzki/twitter-cldr-js/pull/1) against the upstream master. (I'd opened it against my master to have a demonstrably small change-set)

**Pull request merged**
